name: Test Mutation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2']

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: composer install

      - name: Download infection.phar
        run: wget https://github.com/infection/infection/releases/download/0.29.0/infection.phar

      - name: Download infection.phar.asc
        run: wget https://github.com/infection/infection/releases/download/0.29.0/infection.phar.asc

      - name: Import GPG key
        run: gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0

      - name: Verify infection.phar
        run: gpg --with-fingerprint --verify infection.phar.asc infection.phar

      - name: Make infection.phar executable
        run: chmod +x infection.phar

      - name: Run Infection
        env:
          INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}
        run: |
          echo ${{ secrets.INFECTION_DASHBOARD_API_KEY }}
          ./infection.phar --threads=10